name: Daily Commit

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 mins
  workflow_dispatch: # lets you manually trigger it too

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Make a change
        run: |
          echo "$(date)" >> update.log

      - name: Commit and Push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Bennnto"
          git config --global user.email "ben.promkaew@icloud.com"
          git add .
          git commit -m "Daily update $(date)" || echo "Nothing to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
